### ISSUE TITLE
Enforce a specific pin strength

### ISSUE THREAD

**Issue by r4gus** [r4gus/fido2#2]
One could use a simple equation like $E = log_2(R^L)$ to enforce strong pins (also known as passwords. It's not a password-less protocol after all)

https://www.pleacher.com/mp/mlessons/algebra/entropy.html

**Comment by matu3ba** [comment]
This is missing some context: For starters, 
- 1. what character encodings do you assume or support (assume character means grapheme cluster here)
- 2. if normalization and removal of empty space symbols etc must be handled by user or not, see https://github.com/matu3ba/chepa#utf8-whitespace-characters
- 3. pattern influence (leet speech, adding extra symbols in between words) etc

Also, please use the simpler formula `E = L × log2(R).` See https://www.omnicalculator.com/other/password-entropy.

Unless you use LUTs or SIMD, performance will suffer for utf8 and I believe this should not be part of "core" and rather an "extension" due to the size or portability shortcomings.

**Comment by r4gus** [comment]
Thanks for the comment 👍 I was just brainstorming when I wrote this down. Will look into it. You're right that this should be an extension (of the library).

**Comment by r4gus** [comment]
The CTAP2.1 spec states for [setting a new pin](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#settingNewPin) and [changing a existing pin](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#settingNewPin) that: "An authenticator MAY impose arbitrary, additional constraints on PINs. If newPin fails to satisfy such additional constraints, the authenticator returns `CTAP2_ERR_PIN_POLICY_VIOLATION`." 

- newPin is encoded in UTF-8
- newPin must fit into 63 bytes
- the impl currently expects only ASCII chars which is actually a BUG. The min pin length is 4 utf-8 characters and not 4  bytes

I'll add further details soon...

**Comment by r4gus** [comment]
I've added an [optional callback](https://github.com/r4gus/fido2/blob/6e6727a086697ffbd990eff5143e0bd42db4f406/lib/ctap/auth/Callbacks.zig#L77) that is called when setting/ changing a PIN. This should allow users to add additional constraints.

I see three options:

1. We add an extensions folder (library extension; NOT CTAP extension!) somewhere to `lib` and implement a function that calculates `E = L × log2(R)`
2.  We do the same but add it to the Linux reference impl (work in progress) in `platform-auth`
3. Just offer the opportunity to set a callback

**Comment by r4gus** [comment]
I'll close this for now
